name: 'my_new_project'
version: '1.0.0'
config-version: 2
profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  my_new_project:
    # Applies to all files under models/example/
    staging:
      +materialized: table
      +schema: "STAGING"
    transformation:
      +materialized: view
      +schema: "TRANSFORMATION"
    marts:
      +materialized: view
      +schema: "MARTS"
      +required_docs: true
  
on-run-end:
  - "{{ grant_schema_usage_and_select_permissions_to_public(target.database, ['STAGING', 'TRANSFORMATION', 'MARTS']) }}"